GOVERNORATE_CODES = {
    "01": "Cairo",
    "02": "Alexandria",
    "03": "Port Said",
    "04": "Suez",
    "11": "Domiat",
    "12": "Daqahliya",
    "13": "Sharqya",
    "14": "Qalioubya",
    "15": "Kafr El Shekh",
    "16": "Gharbya",
    "17": "Menoufya",
    "18": "Al buhaira",
    "19": "Al Esmaelia",
    "21": "Giza",
    "22": "Beni suef",
    "23": "Fayoum",
    "24": "Minya",
    "25": "Asyut",
    "26": "Suhaj",
    "27": "Qena",
    "28": "Aswan",
    "29": "Luxor",
    "31": "Red Sea",
    "32": "AlWady AlGded",
    "33": "Matrouh",
    "34": "North Sinai",
    "35": "South Sinai",
    "88": "Outside Egypt"
}